# -*- coding: utf-8 -*-
# This file is part of FirmwareDroid - https://github.com/FirmwareDroid/FirmwareDroid/blob/main/LICENSE.md
# See the file 'LICENSE' for copying permission.

FROM firmwaredroid-base-java as apkleaks-worker

#####################################
# Installing jadx                   #
#####################################
RUN mkdir -p /var/jadx/jadx/
WORKDIR /var/jadx/jadx/
# TODO Security enhancement: add checksum check of downloaded zip file
RUN wget https://github.com/skylot/jadx/releases/download/v1.2.0/jadx-1.2.0.zip
RUN unzip ./jadx-1.2.0.zip
ENV JADX "/var/jadx/jadx/bin"
ENV PATH "${JADX}:${PATH}"
RUN export PATH=$PATH

#####################################
# Installing python requirements    #
#####################################
WORKDIR /var/www/
RUN --mount=type=cache,target=/var/www/tmp/.cache \
    pip install -r /var/www/requirements/requirements_apkleaks.txt
