FROM firmwaredroid-base as firmware-worker

USER root
RUN apt-get -y install simg2img && \
    apt-get -y install libfuzzy-dev && \
    apt-get -y install liblzo2-dev && \
    apt-get -y install fuse && \
    apt-get -y install fuseext2
USER $USER_ID:$GROUP_ID

WORKDIR /var/www/
COPY ./ /var/www/

RUN --mount=type=cache,target=/var/www/tmp/firmware/.cache \
    pip install -r ./requirements/requirements_firmware.txt
