# -*- coding: utf-8 -*-
# This file is part of FirmwareDroid - https://github.com/FirmwareDroid/FirmwareDroid/blob/main/LICENSE.md
# See the file 'LICENSE' for copying permission.

FROM firmwaredroid-base as firmware-worker

USER root

# Dependency for libssl1.0.0 -> necessary for .dat patching
RUN echo "deb http://security.debian.org/debian-security jessie/updates main" >> /etc/apt/sources.list
RUN apt-get update

RUN apt-get -y install simg2img && \
    apt-get -y install libfuzzy-dev && \
    apt-get -y install liblzo2-dev && \
    apt-get -y install fuse && \
    apt-get -y install fuseext2 && \
    apt-get -y install brotli && \
    apt-get -y install libssl1.0.0

#WORKDIR /var/www/
#COPY ./ /var/www/

RUN --mount=type=cache,target=/var/www/tmp/firmware/.cache \
    pip install -r ./requirements/requirements_firmware.txt

# TODO refactor this with pypi: https://github.com/hexedit/ext4extract/issues/3
# RUN pip install git+https://github.com/hexedit/ext4extract.git


# TODO security important! Find a way to mount without root user
#USER $USER_ID:$GROUP_ID