FROM firmwaredroid-base as frida-worker

RUN apt-get -y install android-tools-adb && \
    apt-get -y install build-essential gcc musl-dev && \
    adb start-server # Start adb to generate ADB keys

RUN pip install -r ./requirements/requirements_frida.txt