# -*- coding: utf-8 -*-
# This file is part of FirmwareDroid - https://github.com/FirmwareDroid/FirmwareDroid/blob/main/LICENSE.md
# See the file 'LICENSE' for copying permission.
FROM firmwaredroid-base AS firmwaredroid-backend-worker
ENV PATH="/home/www/.cargo/bin:${PATH}"
########################################################
# Copy Source Files                                    #
########################################################
WORKDIR /var/www/
COPY ./ /var/www/

########################################################
# Install Python requirements                          #
########################################################
RUN --mount=type=cache,target=/tmp/.cache \
    pip install -r /var/www/requirements/requirements_backend.txt

########################################################
# Run Webserver                                        #
########################################################
CMD ["/var/www/docker_entrypoint.sh"]