# -*- coding: utf-8 -*-
# This file is part of FirmwareDroid - https://github.com/FirmwareDroid/FirmwareDroid/blob/main/LICENSE.md
# See the file 'LICENSE' for copying permission.

FROM firmwaredroid-base as extractor-worker
USER root

#####################################
# Installing apt dependencies       #
#####################################
RUN apt-get update
RUN apt-get -y install pkgconf && \
    apt-get -y install simg2img && \
    apt-get -y install liblzo2-dev && \
    apt-get -y install fuse && \
    apt-get -y install brotli && \
    apt-get -y install f2fs-tools           # Add support for f2fs filesystem format

#####################################
# Installing unblob dependencies    #
#####################################
RUN apt-get -y install e2fsprogs p7zip-full unar zlib1g-dev liblzo2-dev lzop lziprecover img2simg zstd

#####################################
# Set access rights for mounting    #
#####################################
# TODO Problematic security rights for the user www. Find alternative solution to mounting
RUN echo "www ALL=(root) NOPASSWD: /bin/unmount" >> /etc/sudoers
RUN echo "www ALL=(root) NOPASSWD: /bin/mount" >> /etc/sudoers

#####################################
# Install python dependencies       #
#####################################
USER www
RUN --mount=type=cache,target=/var/www/tmp/.cache \
    pip install -r /var/www/requirements/requirements_extractor.txt

RUN --mount=type=cache,target=/var/www/tmp/.cache \
    pip install -r /var/www/requirements/requirements_backend.txt

ENV PATH "$PATH:/home/www/.local/bin/"

WORKDIR /var/www/source/