# -*- coding: utf-8 -*-
# This file is part of FirmwareDroid - https://github.com/FirmwareDroid/FirmwareDroid/blob/main/LICENSE.md
# See the file 'LICENSE' for copying permission.

FROM firmwaredroid-base-java as super-android-analyzer-worker

USER root
RUN apt-get install -y default-jre-headless
USER $USER_ID:$GROUP_ID

# Download RUST binary
# Note: Update version as well in "super_android_analyzer_wrapper.py" when upgrading the dependency
RUN wget https://github.com/SUPERAndroidAnalyzer/super/releases/download/0.5.1/super-analyzer_0.5.1_ubuntu_amd64.deb
RUN dpkg -i /var/www/super-analyzer_0.5.1_ubuntu_amd64.deb
