# syntax=docker/dockerfile:experimental
FROM firmwaredroid-base as exodus-worker

USER root
RUN apt-get -y install dexdump
USER $USER_ID:$GROUP_ID

RUN --mount=type=cache,target=/var/www/tmp/exodus/.cache \
    pip install -r ./requirements/requirements_exodus.txt

