# -*- coding: utf-8 -*-
# This file is part of FirmwareDroid - https://github.com/FirmwareDroid/FirmwareDroid/blob/main/LICENSE.md
# See the file 'LICENSE' for copying permission.

FROM firmwaredroid-base as exodus-worker

USER root
RUN apt-get -y install dexdump
USER $USER_ID:$GROUP_ID

RUN --mount=type=cache,target=/var/www/tmp/.cache \
    pip install -r /var/www/requirements/requirements_exodus.txt

