# -*- coding: utf-8 -*-
# This file is part of FirmwareDroid - https://github.com/FirmwareDroid/FirmwareDroid/blob/main/LICENSE.md
# See the file 'LICENSE' for copying permission.
FROM firmwaredroid-base as firmwaredroid-backend-worker

########################################################
# Copy Source Files                                    #
########################################################
WORKDIR /var/www/
COPY ./ /var/www/

########################################################
# Install Python requirements                          #
########################################################
RUN --mount=type=cache,target=/tmp/.cache \
    pip install -r /var/www/requirements/requirements_backend.txt

########################################################
# Run Webserver                                        #
########################################################
CMD [ "/home/www/.local/bin/gunicorn", "-w", "17", "--bind", "0.0.0.0:5000", "--worker-tmp-dir", "/dev/shm", "--chdir", "/var/www/source/", "--timeout", "300", "--worker-class", "gevent", "--threads", "12", "--log-level", "debug", "webserver.wsgi:app"]
