FROM firmwaredroid-base as firmware-worker

RUN apt-get -y install simg2img && \
    apt-get -y install libfuzzy-dev && \
    apt-get -y install liblzo2-dev && \
    apt-get -y install fuse && \
    apt-get -y install fuseext2

WORKDIR /var/www/
COPY ./ /var/www/

RUN pip install -r ./requirements/requirements_firmware.txt
