version: '3'
services:
  web:
    build: .
    container_name: flask-web
    working_dir: /var/www
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "5000"
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    depends_on:
      - database
      - redis
    networks:
      - backend
      - frontend

  firmware-worker:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_firmware
    container_name: firmware-worker
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    command: rqworker --name firmware-worker --url redis://redis:6379/ high
    networks:
      - backend
    privileged: true

  firmware-worker-high-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_firmware
    container_name: firmware-worker-high-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    command: rqworker --name firmware-worker-high-1 --url redis://redis:6379/ high
    networks:
      - backend
    privileged: true

  fuzzyhash-worker-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_fuzzyhash
    container_name: fuzzyhash-worker-1
    restart: unless-stopped
    depends_on:
      - redis
      - firmware-worker
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    command: rqworker --name fuzzyhash-worker-1 --url redis://redis:6379/ fuzzyhash
    networks:
      - backend
    privileged: true

  fuzzyhash-worker-2:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_fuzzyhash
    container_name: fuzzyhash-worker-2
    restart: unless-stopped
    depends_on:
      - redis
      - firmware-worker
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    command: rqworker --name fuzzyhash-worker-2 --url redis://redis:6379/ fuzzyhash
    networks:
      - backend
    privileged: true

  fuzzyhash-worker-3:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_fuzzyhash
    container_name: fuzzyhash-worker-3
    restart: unless-stopped
    depends_on:
      - redis
      - firmware-worker
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    command: rqworker --name fuzzyhash-worker-3 --url redis://redis:6379/ fuzzyhash
    networks:
      - backend
    privileged: true

  firmware-worker-default-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_firmware
    container_name: firmware-worker-default-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name firmware-worker-default-1 --url redis://redis:6379/ default
    networks:
      - backend

  firmware-worker-default-2:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_firmware
    container_name: firmware-worker-default-2
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name firmware-worker-default-2 --url redis://redis:6379/ default
    networks:
      - backend

  androguard-worker-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_androguard
    container_name: androguard-worker-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name androguard-worker-1 --url redis://redis:6379/ androguard
    networks:
      - backend

  androwarn-worker-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_androwarn
    container_name: androwarn-worker-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name androwarn-worker-1 --url redis://redis:6379/ androwarn
    networks:
      - backend

  apkid-worker-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_apkid
    container_name: apkid-worker-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name apkid-worker-1 --url redis://redis:6379/ apkid
    networks:
      - backend

  exodus-worker-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_exodus
    container_name: exodus-worker-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name exodus-worker-1 --url redis://redis:6379/ exodus
    networks:
      - backend

  frida-worker-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_frida
    container_name: frida-worker-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name frida-worker-1 --url redis://redis:6379/ frida
    networks:
      - backend

  qark-worker-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_qark
    container_name: qark-worker-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name qark-worker-1 --url redis://redis:6379/ qark
    networks:
      - backend

  quark_engine-worker-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_quark_engine
    container_name: quark_engine-worker-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name quark_engine-worker-1 --url redis://redis:6379/ quark_engine
    networks:
      - backend

  virustotal-worker-1:
    build:
      context: .
      dockerfile: ./docker/workers/Dockerfile_virustotal
    container_name: virustotal-worker-1
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - $PWD:/var/www/
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    env_file:
      - ./.env
    command: rqworker --name virustotal-worker-1 --url redis://redis:6379/ virustotal
    networks:
      - backend

  redis:
    image: redis:6-buster
    container_name: redis
    command: redis-server
    volumes:
      - ${REDIS_DB_PATH}:/var/lib/redis
      - ${REDIS_CONFIG_PATH}:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - backend

  database:
    image: mongo:4.2.8-bionic
    container_name: mongo-db
    restart: unless-stopped
    command: mongod --auth
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - ${LOCAL_DB_PATH}:/data/db
      - $PWD/env/mongo/:/docker-entrypoint-initdb.d/
    networks:
      - backend

  nginx:
    container_name: nginx-frontend
    build:
      context: ./
      dockerfile: Dockerfile_NGINX
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - $PWD/env/nginx:/etc/nginx/conf.d
      - $PWD/env/certbot/conf:/etc/letsencrypt
      - $PWD/env/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

#  certbot:
#    image: certbot/certbot:latest
#    depends_on:
#      - nginx
#    command: certonly --webroot --webroot-path=${CERT_WEBROOT_PATH} --email ${CERT_EMAIL} --agree-tos --no-eff-email -d ${CERT_DOMAIN}
#    volumes:
#      - $PWD/env/certbot/conf:/etc/letsencrypt
#      - $PWD/env/certbot/logs:/var/log/letsencrypt
#      - $PWD/env/certbot/data:/var/www/certbot

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450