########################################################
# Firmwaredroid docker core with java                  #
# Base dependency                                      #
########################################################
FROM openjdk:8-jdk-slim-buster as firmwaredroid-base-java

COPY --from=firmwaredroid-base / /

RUN mkdir -p /var/www/tmp/ && mkdir -p /var/www/
WORKDIR /var/www/
ADD ./ /var/www/
