########################################################
# Firmwaredroid docker core                            #
########################################################
FROM python:3.12-slim-bookworm AS firmwaredroid-base

USER root
ENV GROUP_ID=1000 \
    USER_ID=1000

########################################################
# User generation & directory setup                    #
########################################################
RUN groupadd -r www -g $GROUP_ID && \
    useradd -r -g $GROUP_ID -u $USER_ID www -s /bin/sh -m && \
    mkdir -p /var/www/tmp/ /var/www/ /opt/firmwaredroid/python/ /home/www/.local/bin && \
    chown -R $USER_ID:$GROUP_ID /var/www/ /opt/firmwaredroid/ /home/www

########################################################
# Update installation and apply latest security updates
# - Run apt-get update, upgrade (to apply available security fixes),
#   then install required packages. Use non-interactive frontend.
########################################################
RUN set -eux; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get --allow-releaseinfo-change update -y; \
    # Upgrade packages to pull latest security patches \
    apt-get -y upgrade; \
    # Install essential runtime packages (no compilers to keep image small & secure) \
    apt-get -y install --no-install-recommends \
        apt-utils tar gzip git unzip curl wget sudo; \
    # cleanup apt caches to reduce image size \
    apt-get clean; rm -rf /var/lib/apt/lists/*

########################################################
# Copy Source Files (using --chown to prevent layer duplicate)
########################################################
COPY --chown=www:www requirements.txt /var/www/requirements.txt
COPY --chown=www:www requirements.txt /var/www/requirements_testing.txt
COPY --chown=www:www requirements/ /var/www/requirements/
COPY --chown=www:www source/ /var/www/source/
COPY --chown=www:www docker_entrypoint.sh /var/www/docker_entrypoint.sh
COPY --chown=www:www templates/ /var/www/templates/
COPY --chown=www:www docker/ /var/www/docker/
RUN chmod +x /var/www/docker_entrypoint.sh || true

WORKDIR /var/www/
ENV PATH="$PATH:/home/www/.local/bin/"
ENV PATH="$PATH:/var/www/source/"
ENV PYTHONPATH="/var/www/source/"
ENV DJANGO_SETTINGS_MODULE="webserver.settings"

########################################################
# Install Python dependencies (system-wide)            #
########################################################
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r ./requirements.txt && \
    ln -sf /usr/local/bin/gunicorn /home/www/.local/bin/gunicorn

USER www
