version: '3'
services:
  web:
    volumes:
      - ${DEV_LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    environment:
      - APP_ENV=development

  database:
    volumes:
      - ${DEV_LOCAL_DB_PATH}:/data/db
    environment:
      - APP_ENV=development

  redis:
    volumes:
      - ${DEV_REDIS_DB_PATH}:/var/lib/redis
      - ${DEV_REDIS_CONFIG_PATH}:/usr/local/etc/redis/redis.conf
