version: '3.7'
services:
  web:
    volumes:
      - ${LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
      - ${LOCAL_STORAGE_PATH_SECONDARY}:/var/www/file_store/01_file_storage
    environment:
      - APP_ENV=production

  mongo-db-1:
    container_name: mongo-db-1
    volumes:
      - ${LOCAL_MONGO_DB_PATH_NODE1}:/data/db
    environment:
      - APP_ENV=production
    command: mongod --replSet $MONGODB_REPLICA_SET --auth

  nginx:
    volumes:
      - ./env/certbot/conf:/etc/letsencrypt
      - ./env/certbot/www:/var/www/certbot

  redis:
    container_name: redis
    volumes:
      - ${REDIS_DB_PATH}:/var/lib/redis
      - ${REDIS_CONFIG_PATH}:/usr/local/etc/redis/redis.conf

  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=${CERT_WEBROOT_PATH} --email ${CERT_EMAIL} --agree-tos --no-eff-email -d ${CERT_DOMAIN}
    volumes:
      - ./env/certbot/conf:/etc/letsencrypt
      - ./env/certbot/logs:/var/log/letsencrypt
      - ./env/certbot/data:/var/www/certbot