version: '3'
services:
  web:
    build: .
    container_name: flask-web
    working_dir: /var/www
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "5000"
    volumes:
      - $PWD:/var/www/
      - ${TST_LOCAL_STORAGE_PATH}:/var/www/file_store/00_file_storage
    depends_on:
      - database
      - redis
    networks:
      - backend
      - frontend

  database:
    image: mongo:4.2.8-bionic
    container_name: mongo-db
    restart: unless-stopped
    command: mongod --auth
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - ${TST_LOCAL_DB_PATH}:/data/db
      - $PWD/env/mongo/:/docker-entrypoint-initdb.d/
    networks:
      - backend