# -*- coding: utf-8 -*-
# This file is part of FirmwareDroid - https://github.com/FirmwareDroid/FirmwareDroid/blob/main/LICENSE.md
# See the file 'LICENSE' for copying permission.
"""
Shared secret/config generation logic used by the `init` bootstrap container.

This module intentionally mirrors the generation logic that used to live in the host-side
`setup.py` script (Jinja2 template rendering, self-signed certificate generation, secret
creation), but is designed to run *inside* a container and write its output into a directory
that is expected to be a Docker named volume (e.g. `/config`) instead of the repository
checkout on the host.
"""
from __future__ import annotations

import datetime
import os
import secrets
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

TEMPLATE_FOLDER = Path("/templates") if Path("/templates").exists() else (Path(__file__).resolve().parent.parent.parent / "templates")


def get_template_env() -> Environment:
    """Returns a Jinja2 environment rooted at the bundled templates directory."""
    return Environment(loader=FileSystemLoader(str(TEMPLATE_FOLDER)))


@dataclass
class GeneratedSecrets:
    """
    Container for all secret/derived values generated on first bootstrap.

    These values are never written to the host filesystem. They are persisted only inside the
    `fmd-config` named volume (as `runtime.env` and `secrets/generated-secrets.txt`) and printed
    once to the `init` container's logs.
    """
    redis_password: str = field(default_factory=lambda: os.environ.get("REDIS_PASSWORD") or str(uuid.uuid4()))
    mongodb_initdb_root_username: str = field(default_factory=lambda: os.environ.get("MONGO_INITDB_ROOT_USERNAME") or "mongodbroot")
    mongodb_initdb_root_password: str = field(default_factory=lambda: os.environ.get("MONGO_INITDB_ROOT_PASSWORD") or str(uuid.uuid4()))
    mongodb_username: str = field(default_factory=lambda: os.environ.get("MONGODB_USERNAME") or "mongodbuser")
    mongodb_password: str = field(default_factory=lambda: os.environ.get("MONGODB_PASSWORD") or str(uuid.uuid4()))
    neo4j_password: str = field(default_factory=lambda: os.environ.get("NEO4J_PASSWORD") or str(uuid.uuid4()))
    django_secret_key: str = field(default_factory=lambda: os.environ.get("DJANGO_SECRET_KEY") or secrets.token_hex(100))
    django_superuser_username: str = field(default_factory=lambda: os.environ.get("DJANGO_SUPERUSER_USERNAME") or "fmd-admin")
    django_superuser_password: str = field(default_factory=lambda: os.environ.get("DJANGO_SUPERUSER_PASSWORD") or str(uuid.uuid4()))

    def as_runtime_env(self, domain_name: str) -> str:
        """Renders these secrets as a shell-sourceable `KEY=VALUE` env file."""
        django_superuser_email = f"fmd-admin@{domain_name}"
        lines = [
            "# Auto-generated by the FirmwareDroid init bootstrap container.",
            "# Do not edit by hand; delete the fmd-config volume to regenerate.",
            f"REDIS_PASSWORD={self.redis_password}",
            f"MONGO_INITDB_ROOT_USERNAME={self.mongodb_initdb_root_username}",
            f"MONGO_INITDB_ROOT_PASSWORD={self.mongodb_initdb_root_password}",
            f"MONGODB_USERNAME={self.mongodb_username}",
            f"MONGODB_PASSWORD={self.mongodb_password}",
            f"NEO4J_AUTH=neo4j/{self.neo4j_password}",
            f"DJANGO_SECRET_KEY={self.django_secret_key}",
            f"DJANGO_SUPERUSER_USERNAME={self.django_superuser_username}",
            f"DJANGO_SUPERUSER_PASSWORD={self.django_superuser_password}",
            f"DJANGO_SUPERUSER_EMAIL={django_superuser_email}",
        ]
        return "\n".join(lines) + "\n"

    def as_human_readable(self, domain_name: str) -> str:
        """Renders a human-friendly summary for `secrets/generated-secrets.txt` and logs."""
        return (
            "FirmwareDroid generated credentials (first-run only)\n"
            "=====================================================\n"
            f"Django admin username: {self.django_superuser_username}\n"
            f"Django admin password: {self.django_superuser_password}\n"
            f"Django admin email:    fmd-admin@{domain_name}\n"
            f"Mongo root username:   {self.mongodb_initdb_root_username}\n"
            f"Mongo root password:   {self.mongodb_initdb_root_password}\n"
            f"Mongo app username:    {self.mongodb_username}\n"
            f"Mongo app password:    {self.mongodb_password}\n"
            f"Redis password:        {self.redis_password}\n"
            f"Neo4j password:        {self.neo4j_password}\n"
            "\nRetrieve this file later with:\n"
            "  docker compose cp init:/config/secrets/generated-secrets.txt .\n"
        )


def is_valid_domain_name(domain_name: str) -> bool:
    """Checks if the given domain name is syntactically valid."""
    import re
    return bool(re.match(r"^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$", domain_name))


def generate_certificate(output_path: Path, domain_name: str, port: int | None = None,
                         private_key_filename: str = "privkey.pem",
                         public_key_filename: str = "certificate.pem") -> None:
    """
    Generates a self-signed x509 certificate/key pair and writes them to `output_path`.

    :param output_path: Directory to write the private key and certificate into.
    :param domain_name: Common Name (and SAN-like suffix for non-standard ports) for the cert.
    :param port: Optional port to append to the CN (mirrors legacy setup.py behavior for
        Neo4j's per-connector certificates).
    :param private_key_filename: Output filename for the PEM private key.
    :param public_key_filename: Output filename for the PEM certificate.
    """
    from cryptography import x509
    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives import serialization, hashes
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.x509.oid import NameOID

    output_path.mkdir(parents=True, exist_ok=True)

    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048,
                                           backend=default_backend())

    cn = f"{domain_name}:{port}" if port else domain_name
    subject = x509.Name([
        x509.NameAttribute(NameOID.COUNTRY_NAME, "CH"),
        x509.NameAttribute(NameOID.STATE_OR_PROVINCE_NAME, "Zurich"),
        x509.NameAttribute(NameOID.LOCALITY_NAME, "Winterthur"),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Zurich University of Applied Sciences"),
        x509.NameAttribute(NameOID.COMMON_NAME, cn),
    ])

    certificate = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(subject)
        .public_key(private_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(datetime.datetime.now(datetime.UTC))
        .not_valid_after(datetime.datetime.now(datetime.UTC) + datetime.timedelta(days=1024))
        .sign(private_key, hashes.SHA256(), default_backend())
    )

    private_key_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    )
    certificate_pem = certificate.public_bytes(encoding=serialization.Encoding.PEM)

    (output_path / private_key_filename).write_bytes(private_key_pem)
    (output_path / public_key_filename).write_bytes(certificate_pem)


def generate_cluster_key() -> str:
    """Generates a base64-encoded MongoDB replica-set cluster key."""
    from base64 import b64encode
    from secrets import token_bytes
    return b64encode(token_bytes(756)).decode()


def render_template(env: Environment, template_name: str, output_path: Path, **context) -> None:
    """Renders a Jinja2 template to `output_path`, creating parent directories as needed."""
    template = env.get_template(template_name)
    content = template.render(**context)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
