"""
Django settings for webserver project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import logging
import sys
from datetime import timedelta

import environ
import os
from pathlib import Path
from context.context_creator import setup_logging
from database.connector import init_db
from django.core.exceptions import ImproperlyConfigured

env = environ.Env(
    # set casting, default value
    # DEBUG=(bool, False)
)
BASE_DIR = Path(__file__).resolve().parent.parent.parent
SOURCE_DIR = Path(__file__).resolve().parent.parent
if str(SOURCE_DIR) not in sys.path or sys.path[0] != str(SOURCE_DIR):
    sys.path.insert(0, str(SOURCE_DIR))


# Read .env from base directory if present
if os.path.isfile(os.path.join(BASE_DIR, '.env')):
    environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Also read runtime.env from named volume mount if present
for _runtime_env_candidate in [
    os.path.join(BASE_DIR, 'config', 'runtime.env'),
    '/var/www/config/runtime.env',
    '/config/runtime.env',
]:
    if os.path.isfile(_runtime_env_candidate):
        environ.Env.read_env(_runtime_env_candidate)
        break

APP_ENV = env('APP_ENV', default='development')
if APP_ENV == "production":
    DEBUG = False
    setup_logging(logging.ERROR)
else:
    DEBUG = True
    setup_logging(logging.DEBUG)

DOMAIN_NAME = os.environ.get('DOMAIN_NAME', 'fmd.localhost')
HTTPS_DOMAIN_NAME = "https://" + DOMAIN_NAME
SERVER_NAME = DOMAIN_NAME
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY environment variable is missing or empty. "
        "A secure secret key is required for cryptographic signing."
    )


# Security Settings
ALLOWED_HOSTS = [DOMAIN_NAME,
                 "firmwaredroid-backend:5000",
                 HTTPS_DOMAIN_NAME,
                 "localhost",
                 "fmd.localhost",
                 "fmd.localhost:4443"]
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Strict"
CSRF_TRUSTED_ORIGINS = [HTTPS_DOMAIN_NAME]
CSRF_COOKIE_AGE = 86400

CORS_ALLOWED_ORIGINS = [HTTPS_DOMAIN_NAME,
                        "https://fmd.localhost",
                        "https://localhost",
                        "https://fmd.localhost:4443",
                        "https://fmd.localhost:7687",
                        "https://127.0.0.1"]
CORS_ORIGIN_WHITELIST = [DOMAIN_NAME,
                         "fmd.localhost",
                         "localhost",
                         "127.0.0.1",
                         "https://fmd.localhost",
                         "https://fmd.localhost:4443",
                         "https://fmd.localhost:7687",
                         "https://localhost",
                         "https://127.0.0.1"]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'origin',
    'keep-alive',
    'user-agent',
    'cache-control',
    'content-type',
    'content-transfer-encoding',
    'custom-header-1',
    'x-accept-content-transfer-encoding',
    'x-accept-response-streaming',
    'x-user-agent',
    'x-grpc-web',
    'grpc-timeout',
    'authorization'
]
CORS_ALLOW_METHODS = [
'DELETE',
'GET',
'OPTIONS',
'PATCH',
'POST',
'PUT',
]

CORS_ADDITIONAL_HOST_LIST = [
    host.strip()
    for host in os.environ.get('CORS_ADDITIONAL_HOST', '').split(';')
    if host.strip()
]
for cors_host in CORS_ADDITIONAL_HOST_LIST:
    if not cors_host.startswith("https://") and not cors_host.startswith("http://"):
        cors_host = "https://" + cors_host
    CORS_ORIGIN_WHITELIST.append(cors_host)
    CORS_ALLOWED_ORIGINS.append(cors_host)

CORS_ALLOW_CREDENTIALS = True


SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 86400
SESSION_COOKIE_SAMESITE = "Strict"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "graphene_django",
    "django_rq",
    "corsheaders",
    "setup",
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "webserver.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(SOURCE_DIR, "templates/")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# File Storage Config
_default_file_store = '/var/www/file_store/' if os.path.isdir('/var/www/file_store') else str(BASE_DIR / 'blob_storage') + '/'
MAIN_FOLDER = os.environ.get('FILE_STORE_ROOT', _default_file_store)
if not MAIN_FOLDER.endswith('/'):
    MAIN_FOLDER += '/'
CACHE_FOLDER = ""
IMPORT_FOLDER = ""
IMPORT_FAILED_FOLDER = ""
FIRMWARE_FOLDER_CACHE = ""
LIBS_FOLDER = ""

# Database Config
DB_REPLICA_SET = os.environ.get('MONGODB_REPLICA_SET', 'mongo_cluster_1')
DB_HOST = os.environ.get('MONGODB_HOSTNAME', 'mongo-db-1')
DB_HOST_PORT = int(os.environ.get('MONGODB_PORT', 27017))
DB_NAME = os.environ.get('MONGODB_DATABASE_NAME', 'FirmwareDroid')
DB_AUTH_SRC = os.environ.get('MONGODB_AUTH_SRC', 'admin')
DB_USERNAME = os.environ.get('MONGODB_USERNAME', 'mongodbuser')
DB_PASSWORD = os.environ.get('MONGODB_PASSWORD', '')

DB_URI = ('mongodb://' + DB_USERNAME
         + ':' + DB_PASSWORD
         + '@' + DB_HOST
         + ':' + str(DB_HOST_PORT)
         + '/' + DB_NAME
         + '?authSource=' + DB_AUTH_SRC)

# Database - Settings side-loaded by mongo-engine
MONGO_DATABASES = {
    "default": {
        "db": DB_NAME,
        "name": DB_NAME,
        "host": DB_HOST,
        "password": DB_PASSWORD,
        "username": DB_USERNAME,
        "tz_aware": True,
        "port": DB_HOST_PORT,
        "authSource": DB_AUTH_SRC,
        "authMechanism": "SCRAM-SHA-256"
    },
}

db = init_db(MONGO_DATABASES["default"])

# DJANGO REST API Config
API_TITLE = os.environ.get('API_TITLE', 'FirmwareDroid REST API')
API_VERSION = os.environ.get('API_VERSION', '1.0')
API_DESCRIPTION = os.environ.get('API_DESCRIPTION', 'REST API documentation for the FirmwareDroid service')
API_PREFIX = os.environ.get('API_PREFIX', '/api')
API_DOC_FOLDER = os.environ.get('API_DOC_FOLDER', '/docs')

# FMD - Firmware Mass Import Config
MASS_IMPORT_NUMBER_OF_THREADS = int(os.environ.get('MASS_IMPORT_NUMBER_OF_THREADS', 3))

# Log configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "extractor": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "file_system_indexer": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "fuzzy_hash_creator": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "apk_scanner": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "trufflehog": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

GRAPHQL_JWT = {
    "JWT_VERIFY_EXPIRATION": True,
    "JWT_EXPIRATION_DELTA": timedelta(days=1),
    "JWT_ALLOW_REFRESH": True,
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=7),
    "JWT_COOKIE_NAME": "JWT",
    "JWT_COOKIE_SAMESITE": "Strict",
    "JWT_COOKIE_SECURE": True,
    "JWT_AUTH_HEADER_PREFIX": "Bearer",
    "JWT_PAYLOAD_HANDLER": "webserver.jwt_auth.fmd_jwt_payload",
    "JWT_DECODE_HANDLER": "webserver.jwt_auth.fmd_jwt_decode",
}
GRAPHENE_FRAMEWORK_GRAPHQL_JWT = GRAPHQL_JWT

# Graphql Graphene configuration
GRAPHENE_MIDDLEWARE = [
    "graphql_jwt.middleware.JSONWebTokenMiddleware",
]
if DEBUG:
    GRAPHENE_MIDDLEWARE.append("graphene_django.debug.DjangoDebugMiddleware")

GRAPHENE = {
    "SCHEMA": "api.v2.schema.FirmwareDroidRootSchema.schema",
    "MIDDLEWARE": GRAPHENE_MIDDLEWARE,
}

WSGI_APPLICATION = "webserver.wsgi.application"

# SQL-Lite Test Database of DJANGO - Keep it for the user accounts
DJANGO_SUPERUSER_PASSWORD = os.environ.get("DJANGO_SUPERUSER_PASSWORD", "")
DJANGO_SUPERUSER_USERNAME = os.environ.get("DJANGO_SUPERUSER_USERNAME", "fmd-admin")
DJANGO_SUPERUSER_EMAIL = os.environ.get("DJANGO_SUPERUSER_EMAIL", f"fmd-admin@{DOMAIN_NAME}")
DJANGO_SQLITE_DATABASE_PATH = os.environ.get('DJANGO_SQLITE_DATABASE_PATH', '/var/www/blob_storage/django_database/')
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(DJANGO_SQLITE_DATABASE_PATH, "db.sqlite3"),
    }
}


# Internationalization - see https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images) - see https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "/django_static/"
STATIC_ROOT = os.path.join(SOURCE_DIR, "static/")
FORCE_SCRIPT_NAME = '/'
USE_X_FORWARDED_HOST = True
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type - see https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
# Password validation https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
AUTHENTICATION_BACKENDS = [
    "webserver.jwt_auth.FMDJSONWebTokenBackend",
    "django.contrib.auth.backends.ModelBackend",
]
AUTH_USER_MODEL = "setup.User"

# Redis Config
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')
REDIS_HOST = "redis"  # "localhost" if DEBUG else "redis"

# RQ Config
RQ_QUEUES = {
    'extractor': {
        'HOST': REDIS_HOST,
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': REDIS_PASSWORD,
        'DEFAULT_TIMEOUT': 60 * 60 * 24 * 14,
        'DEFAULT_RESULT_TTL': 60 * 60 * 24 * 3,
    },
    'scanner': {
        'HOST': REDIS_HOST,
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': REDIS_PASSWORD,
        'DEFAULT_TIMEOUT': 60 * 60 * 24 * 14,
        'DEFAULT_RESULT_TTL': 60 * 60 * 24 * 3,
    }
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'webserver.authentication.JWTCookieAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}
